# Generated by Django 4.2.2 on 2024-09-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_policy_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='file',
            field=models.FileField(default=1, upload_to='files/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='policy',
            name='content',
            field=models.TextField(),
        ),
    ]
